### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by IzzySoft** [AkaneTan/libPhonograph#1]
Looks like the license declaration is missing here. As the library is used in Gramophon, that would raise the NonFreeComp (non-free/proprietary component) anti-feature there – but I assume you meant to add GPL-3.0 here as well?

**Comment by nift4** [comment]
Indeed, thank you for the reminder!

**Comment by IzzySoft** [comment]
Thanks for your swift action! Library definition updated on my end so it won't throw a warning :smiley:
